### PR TITLE
Creating project Alexa.NET

### PR DESCRIPTION
**Pull request by timheuer**
Adding PR for considering Alexa.NET for Level 1.  Currently do not use CLA bot as I believe I need permissions to do that?

### CODE REVIEW

**Comment by richlander** [comment]
Thanks! First one!

Couple things:

- There is still one instance of "Tardis".
- Trusted successors are intended to be someone who isn't a maintainer. They are not required for L1 projects.

I'll improve the template to make some of the questions/answers more obvious.

**Comment by timheuer** [comment]
@richlander fixed the typo.  On the successors, that would be good to clarify.  I think the requirement of "each successor must have their own timestamp via git commit" i haven't added the other yet unless/until this would be approved so Steven could do the commit and not on top of a PR of a new doc...if that makes sense.

**Comment by richlander** [comment]
Here is the explanation of trusted successors: https://github.com/dotnet-foundation/project-maturity-model/blob/master/project-continuation-policies.md#trusted-successor

Here is the key text:

> Level 3 projects must register a trusted successor in the case that the maintainer becomes unavailable. The successor can be a specific person or an organization.

If you are going for level 1, you can just delete that whole section for now.

**Comment by richlander** [comment]
This looks good. We now need to fully establish our process for accepting these. I need to talk to some folks first.

**Comment by timheuer** [comment]
Thanks @richlander -- I figured it would be good to live the process and dogfood myself.  It's a small project, but feels right for level 1...

**Pull request closed without merging**
